ACES-CMZ/reduction_ACES

- SB_naming.tsv
These are the proposed shifts from #9
> Proposed shifts

- hipergator_scripts/ghapi_update.py
- hipergator_scripts/run_retrieval.sh
- retrieval_scripts/make_humanreadable_links.py
- retrieval_scripts/retrieve_data.py
- retrieval_scripts/retrieve_weblogs.py
Add new scripts for running regular updates from hipergator
@ashleythomasbarnes you probably will want to make a similar suite of scripts to run on whatever big machine you get access to.  
I will run this daily in a cronjob
> Hipergator scripts

- hipergator_scripts/ghapi_update.py
This will automatically add issues to the project tracker and move them to the right part of the tracker
> Github automation: move around issues in project

- hipergator_scripts/ghapi_update.py
- hipergator_scripts/run_pipeline_slurm_burst_mpi.sh
- retrieval_scripts/retrieve_data.py
* 12M are actually TM1 or TM2
* minor change for pipeline runner
> important fix to regex for ghapi updating

- hipergator_scripts/ghapi_update.py
- hipergator_scripts/run_retrieval.sh
- imaging/mosaic_12m.py
- imaging/mosaic_7m.py
- imaging/mosaic_TP.py
- observation_planning/spectral_shift_planning.py
- retrieval_scripts/retrieve_data.py
And some additional gh-management work
> More updates to mosaic scripts

- pipeline_scripts/recover_tclean_commands.py
- retrieval_scripts/parse_weblog.py
This is a new script to get all the _default_ imaging parameters from the pipeline weblogs.
> Default imaging parameters script

- analysis/spectral_extraction_Feb2022.py
Only path of observations should be changed.
> Update spectral_extraction_Feb2022.py --> spectral_extraction_Mar2022.py

- hipergator_scripts/hack_plotms.py
- hipergator_scripts/run_pipeline_slurm_burst_mpi.sh
FUSE isn't installed on my supercomputer.
To get the ALMA pipeline to run, we therefore need to hack CASA such that it unpacks the AppImage from casaplotms:
http://keflavich.github.io/blog/hacking-plotms-to-let-pipeline-run.html
This PR adds that hack
> Add a "hack plotms" code

- hipergator_scripts/delivery_status.py
- hipergator_scripts/job_runner.py
- hipergator_scripts/run_cube_stats_grid.sh
- hipergator_scripts/run_reimaging_script.sh
- hipergator_scripts/run_script_generator.sh
- hipergator_scripts/run_simple_script.sh
- imaging/write_tclean_scripts.py
- pipeline_scripts/merge_tclean_commands.py
- pipeline_scripts/override_tclean_commands.json
This PR adds several missing scripts and fixes some bugs and improves the flexibility of the pipeline.
> Various updates to pipeline pieces

- hipergator_scripts/ghapi_update.py
Now the reprocessed files will be updated.  Previously,  there was only a boolean check for whether there were reprocessed files or not - now they are updated each time as new ones are added.
Also, reclean directories are included in the reprocessed list.
> ghapi updates

- aces/pipeline_scripts/override_tclean_commands.json
Added changes to cyclefactor for SPWs 20 & 24.
> Adding parameters for Sgr_A_st_ai_03_7M #143

- aces/pipeline_scripts/override_tclean_commands.json
Updating tclean parameters for #35, #14, #139
> Update tclean params

- aces/pipeline_scripts/override_tclean_commands.json
This should fix remaining divergence divergence problems in issue #149.   I tested on 10 channels of SPW 27.
> change usemask and pb values to fix the lingering divergence issues

- aces/hipergator_scripts/delivery_status.py
- aces/hipergator_scripts/run_mosaic_12m.sh
- aces/hipergator_scripts/run_mosaic_7m.sh
- aces/hipergator_scripts/run_mosaic_TP.sh
- aces/imaging/make_mosaic.py
- aces/imaging/mosaic_12m.py
- aces/imaging/mosaic_TP.py
- aces/imaging/write_tclean_scripts.py
- setup.cfg
> Scripting updates

- aces/pipeline_scripts/override_tclean_commands.json
Updated channel widths, nchans, and cleaning thresholds for SPWs 25, 27, 29, 31 & 35 for Sgr_A_st_as_03_TM1 (#145).
> Updated channel parameters to undo size mitigation for region as (#145)

- aces/analysis/cube_stats_grid.py
- aces/analysis/imstats.py
- aces/hipergator_scripts/job_runner.py
- aces/hipergator_scripts/run_cube_stats_grid.sh
- aces/imaging/mosaic_TP.py
- aces/imaging/write_tclean_scripts.py
- aces/pipeline_scripts/generate_spw33_commands.py
- aces/pipeline_scripts/override_tclean_commands.json
- setup.cfg
Updating the cube stats code so it runs
> Cube stats

- tox.ini
I've added exceptions for the code in #294 and #291 to remove the need to do line-by-line exceptions in the scripts in those PRs. 
@keflavich I'm not sure if the change I've made to the tox.ini file here is necessarily the correct way to implement it, so it'd be great if you could take a look for me. Thanks!
> Added exceptions to tox.ini

- aces/pipeline_scripts/override_tclean_commands.json
Cyclefactor from 2.5 to 3.5. Issue #257
> Updating cycle factor for Sgr_A_st_o_03_7M

- aces/analysis/cube_stats_grid.py
- aces/hipergator_scripts/ghapi_update.py
- aces/hipergator_scripts/job_runner.py
- aces/hipergator_scripts/run_imstats.sh
- aces/hipergator_scripts/run_script_generator.sh
- aces/imaging/mosaic_12m.py
- aces/imaging/mosaic_7m.py
- aces/imaging/write_tclean_scripts.py
- aces/pipeline_scripts/generate_aggregate_high_commands.py
- aces/pipeline_scripts/generate_spw33_commands.py
- aces/pipeline_scripts/override_tclean_commands.json
- aces/retrieval_scripts/retrieve_data.py
- tox.ini
> Minor bugfixes, new pars

- aces/pipeline_scripts/override_tclean_commands.json
One channel (620) still shows divergence. Updating cyclefactor from 3.5 to 4.0 #257
> Updating cyclefactor for Sgr_A_st_o_03_7M  #257

- aces/pipeline_scripts/override_tclean_commands.json
I use cyclefactor = 2 to fix divergence at channel 668
> reclean 7m spw 24 SB=Sgr_A_st_y_03_7M

- aces/pipeline_scripts/override_tclean_commands.json
overdue niter increase for issue #228
> Reclean 228

- aces/pipeline_scripts/override_tclean_commands.json
Updated tclean commands (cyclefactor) to avoid divergence in SPW 33 for Sgr_A_st_e_03_TM1 (#147).
> Updated tclean commands for SPW 33 for #147

- aces/hipergator_scripts/job_runner.py
- aces/imaging/write_tclean_scripts.py
updated MSes weren't running properly
> Bugfix june19 updated

- aces/pipeline_scripts/override_tclean_commands.json
Raised spw33 cyclefactor to resolve divergence
> Updated clean parameters for reimaging of Sgr_A_st_d_03_TM1

- aces/retrieval_scripts/globus_cli_template_totalpower.sh
another example for getting total power data from globus
> expanded example

- aces/pipeline_scripts/override_tclean_commands.json
Increase cyclefactor from 1.0 -> 2.5 for SPW 33 for #256 in an attempt to resolve divergence in this SPW.
> Increase cyclefactor for region c spw33 (#256)

- aces/joint_deconvolution/cube_utils.py
- aces/joint_deconvolution/feather_funcs.py
Accidentally left an if statement in the feathering loop that was used for testing a single region. This has now been removed.
> Bug fixes for feathering scripts

- aces/pipeline_scripts/override_tclean_commands.json
Edited override_tclean_commands.json file to include updated tclean commands for Sgr_A_st_o_03_TM1, spw33
> Updated tclean parameters for re-imaging of Sgr_A_st_o_03_TM1, spw33

- aces/joint_deconvolution/reproject_mosaic_funcs.py
Updated `weighted_reproject_and_coadd` function to use astropy's `fits` functionality for cube reading/writing. As noted by @ashleythomasbarnes, `spectral_cube` was filling up the `/tmp/` directory resulting in a core dump and CASA crashing.
> Update mosaicking function

- aces/analysis/spectral_extraction_everywhere.py
- aces/imaging/make_mosaic.py
- aces/imaging/mosaic_12m.py
@jenwalls This code implements spectral extraction for all dendrogram objects.  Right now it's doing it both in elliptical apertures and using the dendrogram masks.
> Spectral extraction

- aces/pipeline_scripts/override_tclean_commands.json
Updated channel parameters for #150 (Sgr_A_st_b_TM1). SPW 33 is fine, this is for all other SPWs.
> Undo size mitigation for #150

- aces/pipeline_scripts/override_tclean_commands.json
> Update tclean params 149

- aces/analysis/tp_baseline_sub.py
- aces/joint_deconvolution/feather_all_spws.py
- aces/joint_deconvolution/feather_mopra_hcop.py
Scripts for doing the general ALMA 12m+7m+TP feathering and the 12m+7m+MOPRA feathering.
I probably should have split the common functions out to avoid repetition, but I didn't ...
EDIT: also added the TP baseline correction script here. Bad use of git, but saves opening a new PR ...
> Add general feathering script and hcop MOPRA feathering script

- aces/pipeline_scripts/override_tclean_commands.json
Bumping up the cyclefactor for field am, spw33, to hopefully fix the divergence in channel ~ 670.
> Update cyclefactor from 2.5 to 3.0 for field am spw33

- aces/imaging/12m-7mPlusTP-feather.py
This script does feather and mosaic of 12m and existing 7m/TP feathered cubes.
> script to combine 12m and 7m plus TP cubes
