ACES-CMZ/reduction_ACES

aces/pipeline_scripts/generate_aggregate_high_commands.py

To try to address the beam size issues noted elsewhere, we can use only the high-frequency, broad-bandwidth windows to produce our continuum images.

Generate continuum from only CONT spws (33,35)

---

aces/pipeline_scripts/override_tclean_commands.json

This fixes the divergence on SPWs 24 and 26 in issue #19.  Increasing cyclefactor to 3 worked. Tested on 10 channels per spw that included some previously bad cleans and they came out ok.

fix tclean divergence for field ar

---

aces/pipeline_scripts/override_tclean_commands.json

spw35 ao was giving this error:
```
2022-10-03 14:39:00     SEVERE  tclean::::casa  Task tclean raised an exception of class RuntimeError with the following message: Error in running Major Cycle : Cannot open existing image : /blue/adamginsburg/adamginsburg/ACES/workdir/ao_spw35_cube_TM1_A001_X15a0_X190/uid___A001_X15a0_X190.s38_0.Sgr_A_star_sci.spw35.cube.I.iter1.reclean.model : There is a shape mismatch between existing images ([1024, 2592, 1, 3834]) and current parameters ([1024, 2592, 1, 1916]). If you are attempting to restart a run with a new image shape, please change imagename and supply the old model or mask as inputs (via the startmodel or mask parameters) so that they can be regridded to the new shape before continuing.
2022-10-03 14:39:00     SEVERE  tclean::::casa  Exception …
```

Fix ao spw35 parameters

---

aces/pipeline_scripts/override_tclean_commands.json

Updated channel widths, nchans, and cleaning thresholds for SPWs 25, 27, 29, 31 & 35 for Sgr_A_st_ac_03_TM1 (https://github.com/ACES-CMZ/reduction_ACES/issues/232).

Updated channel parameters to undo size mitigation for region ac (#232)

---

aces/pipeline_scripts/override_tclean_commands.json

Updated channel widths, nchans, and cleaning thresholds for SPWs 25, 27, 29, 31 & 35 for Sgr_A_st_ad_03_TM1 (https://github.com/ACES-CMZ/reduction_ACES/issues/28).

Updated channel parameters to undo size mitigation for region ad (#28)

---

aces/pipeline_scripts/override_tclean_commands.json

Updated channel parameters and cleaning thresholds for SPWs 25, 27, 29, 31, and 35 to undo size mitigation for region Sgr_A_st_h_03_TM1 (#142).
Also increased cyclefactor to 2.0 for SPW 33 as it diverged with the default value.

Update chan params for region h #142

---

aces/pipeline_scripts/override_tclean_commands.json

Updated channel parameters and threshold for cubes for SPWs 25, 27, 29, and 31. 
This is for Sgr_A_st_ao_03_TM1 (#41), which is in addition to the changes made by Pei-Ying/Adam (#274) for SPWs 33 & 35.

Updating channel parameters for #41

---

aces/pipeline_scripts/override_tclean_commands.json

Updated channel parameters and thresholds for SPWs 25, 27, 29, 31 to undo size mitigation for Sgr_A_st_v_03_TM1 (#235). SPW 33 and 35 were already done.

Update tclean cube params for region v_TM1

---

aces/pipeline_scripts/override_tclean_commands.json

Updated channel parameters and cleaning thresholds for SPWs 25, 27, 29, 31, and 35 to undo size mitigation for region Sgr_A_st_n_03_TM1 (https://github.com/ACES-CMZ/reduction_ACES/issues/231).

Update tclean cube params for region n_TM1

---

aces/analysis/cube_stats_grid.py
aces/analysis/imstats.py
aces/analysis/spectral_extraction_Feb2022.py
aces/analysis/spectral_extraction_Nov2022.py
aces/hipergator_scripts/ghapi_update.py
aces/hipergator_scripts/run_cube_stats_grid.sh
aces/hipergator_scripts/run_imagingpipeline_inplace.sh
aces/hipergator_scripts/run_imstats.sh
aces/imaging/mosaic_12m.py
aces/imaging/write_tclean_scripts.py
aces/pipeline_scripts/generate_spw33_commands.py
aces/pipeline_scripts/override_tclean_commands.json
aces/retrieval_scripts/retrieve_weblogs.py
tox.ini

The pipeline version used for ALMA-pipeline-based reimaging, which was not used for everything but may be used for 7m data, was using CASA 6.2 instead of 6.4.  This updates to use 6.4 instead.
The overall reimaging is using `casa-6.4.4-31-py3.8` rather than `casa-6.4.3-2-pipeline-2021.3.0.17`.  I'm not sure when I made that decision, but I should have documented it better.  Using a non-pipeline version of CASA is slightly preferable because it has faster startup, but that means there is an inconsistency in the versions used for imaging.
Other fixes in this PR are small but critical typo fixes.  Notably, the weblog links should go straight to the weblog instead of the folder containing the html/ folder from now on.

Various script updates, incl. pipeline version change

---

aces/joint_deconvolution/make_region_list.py

This is a crude script to pull from [default_tclean_commands.json ](https://github.com/ACES-CMZ/reduction_ACES/blob/main/aces/pipeline_scripts/default_tclean_commands.json)file to grab all region names and corresponding 12m & 7m MOUS IDs. This information is written out to a .csv file containing the following columns:
- Region name (with unnecessary text trimmed, e.g. "_updated"/"_03_TM1")
- Original, untrimmed 12m region name (for querying .json file in array combination cleaning script, #291)
- 12m MOUS ID (e.g. uid___A001_X1590_X30aa)
- Original, untrimmed 7m region name
- 7m MOUS ID
I've been using this script to generate the region & MOUS ID list in order to read it into the [array combination script](https://github.com/ACES-CMZ/reduction_ACES/pull/291/files#diff-8327e51a76630ef05c081 …

Added script to parse json file to retrieve region names and MOUS IDs

---

aces/joint_deconvolution/clean_HNCO_12m_7m.py

Increased cyclefactor from 1.5 -> 2.5. I found that using 1.5 resulted in divergence very often. 2.5 seems to fix this for the majority of cases, at the expense of efficiency. 
Since I was grabbing the default 12m parameters, the channel parameters were often for the size-mitigated products. I was previously using a clunky if statement to scale the parameters appropriately, but in a few cases this failed because CASA complained about the channel width being ever-so-slightly different than what it expected. I've now just set them all to blank/default instead.

Minor update to increase cyclefactor and use default channel parameters

---

aces/pipeline_scripts/override_tclean_commands.json

Reclean parameters for Sgr_A_st_e_updated_03_7M (#168 )
However, the reclean has been run on local machines and the image cubes have been uploaded to globus, so it is not necessary to trigger the reclean.

reclean parameters for Sgr_A_st_e_updated_03_7M

---

aces/pipeline_scripts/override_tclean_commands.json

Reclean parameters for Sgr_A_st_p_03_7M (#148 )
However, the reclean has been run on local machines and the image cubes have been uploaded to globus, so it is not necessary to trigger the reclean.

reclean parameters for Sgr_A_st_p_03_7M

---

aces/retrieval_scripts/globus_cli_template.sh

This is an example template for using the [Globus CLI](https://docs.globus.org/cli/) to transfer data from HPG to a local machine. This specific example was used for transferring the 12m HNCO fits files, and uses [aces_SB_uids.csv](https://github.com/ACES-CMZ/reduction_ACES/blob/b0e74276fd5340ae7ae0a8d85e153e8ea4ba6561/aces/data/tables/aces_SB_uids.csv) to get the list of SB uids. This is designed to work with a directory structure that directly mirrors the HPG directory structure.
To use this, you'll need to update your endpoint IDs and paths accordingly, and obviously update the query parameters to suit your needs.
If anyone has any suggested updates/improvements, that'd be great. This method is a bit awkward, and relies on using `ls` to query globus, writing the output to a text file, …

Add globus cli script

---

aces/pipeline_scripts/override_tclean_commands.json

Updating tclean parameter for Sgr_A_st_ao_03_7M, spw24: cyclefactor from 1.0 to 2.0 (issue #6) But please note that I have run the reimaging on a local machine and have uploaded the images to Globus. This commit is just for bookkeeping, there is no need to rerun the pipeline on hipergator.

Updating tclean parameter for region ao 7M

---

aces/pipeline_scripts/override_tclean_commands.json

Increase `cyclefactor` from 1.0 to 2.0 for SPW 33 for region as (#145) to fix mild divergence (https://github.com/ACES-CMZ/reduction_ACES/issues/145#issuecomment-1596260305).

Update cyclefactor for region 'as' SPW 33 (#145)

---

aces/pipeline_scripts/override_tclean_commands.json

Increase from default `cyclefactor` value to 2.5 in an attempt to avoid divergence in SPW 33 for region `ao` (the Brick, #41).

Increase cyclefactor for SPW 33 (#41)

---

aces/pipeline_scripts/override_tclean_commands.json

Follow up to tracking in #179.
Updated channel parameters for regions `aa`, `d`, `g`, `l`, and `r` to undo spectral binning size mitigation in relevant SPWs.

Undo size mitigation for various 12m SBs

---

aces/pipeline_scripts/override_tclean_commands.json

Updated the override_tclean_parameters .json file to include the tclean parameters used to resolve divergence in SPW 35 of TM1 region o.

Updated tclean parameters for re-imaging TM1 region o, SPW 35

---

aces/joint_deconvolution/joint_deconv_funcs.py
aces/joint_deconvolution/run_joint_deconv_tests.py

Scripts for running various tests for improving joint deconvolution of 12m & 7m data (see #384).
The code works, but still needs improvements.
Additions in progress:
- Using TP cube as a startmodel. Basic outline is in place, but commented out. 
- `tclean` does not handle the regridding as expected and fails. 
- `imregrid` works fine, but requires an existing template. 
- Initial idea is to create a dirty image of the 12m + 7m data, use this as a template for regridding the TP data, then proceeding with the joint deconv + TP startmodel. But there's probably a more efficient (non-casa?) way to regrid the TP data?
- Currently using `default_tclean_commands.json`. Need to update to merge with override commands.
- I'm still exploring the possibility of a multi-stage masking procedure as …

Add scripts for running joint deconvolution tests

---

aces/pipeline_scripts/override_tclean_commands.json

Update override commands to add nchan and width parameters for region aq (#140) for SPWS 25, 27, 29, 31, 25.
Note: Once merged, no action is needed. This is for bookkeeping only, as the un-mitigated files already exist.

undo size mitigation for aq (#140)

---

aces/joint_deconvolution_cont/crop.py
aces/joint_deconvolution_cont/feather.py
aces/joint_deconvolution_cont/finalise.py
aces/joint_deconvolution_cont/process_alma.py
aces/joint_deconvolution_cont/process_mustang.py

scripts to feather ALMA 12m + GBT

---

aces/pipeline_scripts/override_tclean_commands.json

Increase cyclefactor to 2.0 for field `ah` (#238) SPW 33 to fix divergence in CS.
(Ignore the incorrect field ID in the branch name ...)

Increase cycle factor for Sgr_A_st_ah_03_TM1 SPW 33 (#238)
